language: cpp
compiler: gcc
dist: bionic

# Handle git submodules yourself
git:
    submodules: false
    
before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
  #- tar -xvf lcov-1.14.tar.gz
  #- cd lcov-1.14 && sudo make install
  #- cd ..

install: 
  - sudo apt-get install -qq g++-9
  - sudo apt-get install -qq gcc-9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
  - sudo apt-get install cmake
  - sudo apt-get install libperlio-gzip-perl
  - sudo apt-get install libjson-perl
  - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
  - sudo apt-get install libpthread-stubs0-dev
  - sudo apt-get install libpng-dev
  - 
  - git clone https://github.com/linux-test-project/lcov.git
  - cd lcov
  - sudo make install
  - cd ..
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.16.5-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.16.5-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ..

script:
  - export CODECOV_TOKEN="c30d709d-2ae8-4b64-9cca-e38d646efee3"
  - mkdir -p build && cd build
  - cmake -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=OFF ..
  - cmake --build . --config Debug -- -j $(nproc)
  - ctest -j $(nproc) --output-on-failure

after_success:
# Create lcov report
# capture coverage info
  - lcov --gcov-tool /usr/bin/gcov-9 --capture --directory . --output-file coverage.info --no-external
# filter out system and extra files.
  - lcov --remove coverage.info '/usr/*' '*/libs/*' '*/tests/*' --output-file coverage.info
# output coverage data for debugging
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
